/* ============ EPILOGHI PERSONALI E IMPRESE (achievement) ============ */

const HERO_EPILOGUES = {

  torvald: {
    vittoria: `Torvald tornò a Brindolo con il martello ancora caldo e aprì finalmente la locanda dei suoi sogni: "Il Martello e il Mestolo", dove il menù è fisso, la porzione è abbondante e chi si lamenta della cottura viene invitato — gentilmente — a uscire e ripensarci. Le pareti si riempirono presto di armi da guerra riconvertite in posate giganti e di una statua di sé stesso, offerta dal Comune, che lui trova "lusinghiera ma con le spalle sproporzionate". Ogni sera racconta la battaglia contro Vesper a chiunque ordini lo stufato, aggiungendo un dettaglio nuovo — e sempre più eroico — a ogni versione.`,
    redenzione: `Quando Vespertino Morn iniziò a suonare ogni venerdì al Gallo Storto, Torvald si offrì — "per il bene della locanda, non perché mi sia affezionato al vampiro" — di curare il buffet dei concerti. Inventò lo "Stufato del Pubblico Sordo", diventato il piatto più richiesto della regione. I due litigano regolarmente su cosa serva davvero a un artista per esibirsi al meglio (Torvald dice: pancia piena; Vespertino dice: silenzio rispettoso), ma quando le luci si abbassano è sempre Torvald, tra i tavoli, il primo ad applaudire più forte di tutti — e a fingere di non commuoversi.`,
    esilio: `Torvald aprì comunque la sua locanda — il sogno non aspetta il lieto fine di qualcun altro — e la chiamò "Il Sole Ritrovato", in onore della notte più lunga della sua vita. Tiene un tavolo permanentemente apparecchiato per un ospite che forse non tornerà mai: "Non si sa mai, un vampiro pallido e affamato di zuppa." Quando i viandanti raccontano di aver sentito un liutista sconosciuto cantare in qualche taverna di frontiera, Torvald si limita ad annuire e a preparare una porzione in più, "giusto per sicurezza". Nessuno osa più lamentarsi del suo stufato. Nessuno ci ha mai provato due volte.`,
  },

  lyra: {
    vittoria: `Lyra tornò all'Accademia con un rapporto dettagliato — "in tredici capitoli, con note a piè di pagina" — sulla sconfitta di un vampiro incoronato, e l'Arcimaga Selestra fu costretta a riammetterla con tanto di scuse pubbliche. Lyra ascoltò l'intero discorso di riammissione, annuì compostamente... e rifiutò. "Ho già l'unico laboratorio che conta: il mondo," dichiarò, richiudendosi il taccuino esplosivo sotto il braccio prima di tornare sulla strada coi compagni. L'Accademia le dedicò comunque un'aula. Lei non l'ha mai vista: era troppo occupata a far esplodere qualcos'altro, altrove, con debito permesso.`,
    redenzione: `Ai concerti del venerdì, Lyra cura le luci: fuochi fatui incantati che danzano sopra il palco di Vespertino a tempo di musica — "pura fisica applicata," insiste, ignorando chi la chiama "scenografia". L'Accademia le ha offerto una cattedra dopo aver saputo della corona distrutta; lei ha risposto con un incantesimo dimostrativo che ha fatto saltare tre finestre della sala del consiglio, allegando un biglietto: "Ripensateci." Tiene un intero capitolo del taccuino dedicato a "Cosa NON fare con una corona magica senziente", che vende a caro prezzo ad altri maghi. È, a modo suo, felicissima.`,
    esilio: `Lyra non tornò mai all'Accademia: pubblicò da sola un trattato — "Della Corona di Mezzanotte e degli Errori Altrui" — che l'Arcimaga Selestra lesse, si dice, tre volte prima di scrivere una lettera di scuse mai spedita. Lyra viaggia ancora col taccuino esplosivo, sempre più pieno, sempre più pericoloso da aprire. Di tanto in tanto incrocia voci su un menestrello pallido che canta nelle locande di frontiera, e si chiede, con genuina curiosità accademica, quale incantesimo tenesse insieme corona e vampiro per duecento anni. Non lo scoprirà mai del tutto. Le piace così.`,
  },

  fizzle: {
    vittoria: `Con la reputazione da eroe e la borsa più pesante di sempre, Fizzle fece finalmente la cosa che rimandava da anni: consegnò la lettera d'amore. La destinataria — una fioraia di Brindolo di nome Rosalba — la lesse, arrossì, e gli chiese perché diamine ci avesse messo così tanto. Fizzle, per una volta nella vita, non ebbe una battuta pronta. I due si vedono ogni martedì; lui le porta sempre qualcosa "ricollocato con stile" da un'avventura, lei finge di non saperlo. Il 60% del maltolto, promette, va ancora in beneficenza. Il restante 40%, ora, va in fiori.`,
    redenzione: `Fizzle si autonominò "agente ufficiale" di Vespertino Morn, ruolo che consiste soprattutto nel vendere gadget non autorizzati — corone di latta, sold out ogni venerdì — e nel negoziare col bagarinaggio dei biglietti, lavoro che svolge con l'autorità morale di un ex bagarino pentito. Ha finalmente consegnato la sua vecchia lettera d'amore, ispirato dal secondo atto di Vespertino: "Se un vampiro può reinventarsi, posso farlo anch'io." La fioraia Rosalba ora vende fiori proprio davanti al Gallo Storto, ogni venerdì sera. Coincidenza? Fizzle giura di sì. Nessuno gli crede.`,
    esilio: `Fizzle rintraccia il menestrello esiliato una volta l'anno, non si sa mai come: gli lascia sempre qualcosa di utile — una moneta, una coperta, una volta un intero liuto "ricollocato da un nobile che comunque non lo suonava" — e sparisce prima dell'alba, esattamente come fa Vesper. Nessuno dei due lo ammetterà mai, ma è la cosa più simile a un'amicizia che entrambi si concedano. Quanto alla lettera d'amore: consegnata, finalmente, alla fioraia Rosalba, che ha risposto con un mazzo di fiori e la domanda che tutti si aspettavano — "Ma quanto ci hai messo?"`,
  },

  brunilde: {
    vittoria: `Brunilde tornò al convento di Santa Aurora aspettandosi una ramanzina per il mazzafrusto, e ricevette invece una promozione: la Madre Superiora la nominò "Guardiana della Luce Errante", titolo che lei trova "pomposo ma onestamente meritato". Continua a benedire tutto, nemici compresi, e a menare con entusiasmo pastorale chiunque minacci la pace di Lumelia. Il suo primo atto ufficiale da promossa è stato presentare reclamo scritto contro "l'insulto personale" subito dal sole spento — reclamo accolto, sei mesi dopo, con tanto di scuse cosmiche informali. Le altre suore la temono e la adorano in proporzioni quasi uguali.`,
    redenzione: `Ispirata dalla seconda vita di Vespertino, Brunilde fondò un nuovo ordine: le Suore dell'Alba Operosa, dedicate a chi merita una seconda possibilità e a chi, semplicemente, ha bisogno di una sana energia mattutina applicata con un candelabro. Officia personalmente il concerto del venerdì con una breve benedizione prima del bis — "Che la luce, e la musica, vi accolga. ADESSO." — e tiene un occhio vigile su Vespertino, nel caso ricadesse in vecchie abitudini teatrali. Non è mai successo. Ma lei resta pronta, mazzafrusto a portata di mano, "per principio, non per sfiducia".`,
    esilio: `Brunilde non approvò l'esilio — "la clemenza senza redenzione è solo pigrizia con una buona pubblicità," dichiarò al Consiglio, che finse di non sentire — e da allora dedica un pellegrinaggio l'anno a cercare il menestrello errante, nella speranza di convincerlo a tornare e "fare ammenda come si deve". Non ci è ancora riuscita. Nel frattempo ha fondato comunque le Suore dell'Alba Operosa, "per tenersi in esercizio", e benedice ogni villaggio che attraversa con lo stesso entusiasmo con cui menerebbe un demone. Il mazzafrusto, dice, è anche un ottimo bastone da pellegrino. Soprattutto per un pellegrino di taglia forte.`,
  },

  kael: {
    vittoria: `Sul palco per la consegna della statua, al sindaco Bartolo che gli chiede due parole, Kael pronuncia la frase più lunga della sua vita pubblica: "Biscotto e io... abbiamo degli amici. Cinque, per la precisione. Sei, contando il tasso." Il pubblico applaude, Biscotto rifiuta di scendere dalla sua spalla per il resto della cerimonia, e il Consiglio di Brindolo conia — su richiesta ufficiale di Zonk — una medaglietta per "Servizio Eroico e Morsi Tempestivi". Kael porta ancora il mantello, medita ancora molto, ma ha smesso di definirsi "un lupo solitario". Ora dice "due lupi", e basta.`,
    redenzione: `Kael si presenta ai concerti del venerdì sempre allo stesso tavolo d'angolo, sempre con la scusa di "tenere d'occhio la situazione". Biscotto, meno interessato alla sicurezza e più al buffet di Torvald, ha sviluppato una tecnica di furto di crostini leggendaria tra il personale. Vespertino gli ha dedicato una strofa segreta della Ballata — "al ranger che non applaude ma resta fino alla fine" — e Kael, che nega di averla notata, la canticchia distrattamente quando pensa che nessuno ascolti. Nessuno glielo dice. Fa ormai parte del suo fascino misterioso, ufficialmente riconosciuto come tale dal resto del gruppo.`,
    esilio: `Da bravo ranger, Kael continua a seguire — a distanza, senza farsi vedere, "per abitudine professionale" — le tracce del menestrello esiliato attraverso il regno. Ogni tanto torna a Brindolo con notizie: "Ha cantato a Ponte Vecchio. Bene, ma la seconda strofa era stanca." Biscotto lo accompagna sempre, ha imparato a riconoscere l'odore del mantello di Vesper da un miglio, e una volta gli ha restituito un bottone perduto senza che nessuno glielo chiedesse. Kael sostiene di non provare simpatia per un ex-vampiro. Il gruppo sostiene che i suoi rapporti di viaggio siano sempre, sospettosamente, molto dettagliati.`,
  },

  zonk: {
    vittoria: `Zonk vinse la mostra di ricamo di Villa Petunia con un arazzo enorme — categoria "scene epiche", sezione creata apposta per lui — raffigurante l'intera avventura, ragni compresi (ricamati piccolissimi, in un angolo, "per esposizione controllata"). Durante la premiazione un ragno vero, sfuggito da una cassa di frutta, gli è passato vicino: Zonk è rimasto quasi fermo un secondo intero prima di salire su un tavolo urlando con dignità. La statua in piazza lo ritrae con i fiorellini all'uncinetto, come richiesto espressamente. Dice che è "il giorno più bello della sua vita, dopo il torneo e il ricamo". Nell'ordine giusto.`,
    redenzione: `Zonk realizza sciarpe ricamate per ogni concerto di Vespertino — una diversa a settimana, sempre con una nota musicale e un piccolo sole, "perché il tema deve essere chiaro" — e le vende al banchetto insieme ai goblin del guardaroba. È diventato, suo malgrado, l'accessorio di moda più ambito di Lumelia. Ai bambini del coro insegna il punto croce dopo le prove; dice che "condividere la merenda e il ricamo" sia la vera ricetta per una pace duratura, e finora nessuno ha trovato controesempi validi. La sua paura dei ragni resta intatta, ma ora la definisce "una fase", con encomiabile ottimismo.`,
    esilio: `Zonk finì comunque l'arazzo dell'avventura, ma lasciò un angolo vuoto, "per quando la storia si completa". Ogni tanto lo porta con sé ai mercati, nella vaga speranza che il menestrello esiliato lo veda e capisca di essere ancora, in qualche modo, parte della trama. Ha anche spedito, tramite un mercante di fiducia, una sciarpa ricamata con una nota musicale e la scritta "Anche i cattivi meritano di stare al caldo". Non ha mai ricevuto risposta. In fondo non se l'aspettava. Nel frattempo ha vinto comunque la mostra di ricamo di Villa Petunia, ragni quasi affrontati con successo.`,
  },

};

const IMPRESE = [
  // ---- flag già esistenti in campaign.js / CAPRA_SCENES ----
  { flag: 'reputazione',        icon: '📢', title: 'Idolo della Piazza',            desc: 'Avete calmato Brindolo nel giorno in cui il sole si è spento.' },
  { flag: 'sa_magia',           icon: '🔮', title: 'Detective dell\'Apocalisse',    desc: 'Avete capito al volo che il sole non si è spento: ve l\'hanno rubato.' },
  { flag: 'stufato_bonus',      icon: '🍲', title: 'A Pancia Piena',                desc: 'Avete finito lo stufato mentre il mondo finiva. Priorità sacrosante.' },
  { flag: 'eroici',             icon: '⚔️', title: 'Eroi Senza Contrattare',        desc: 'Avete accettato la missione senza discutere sul prezzo.' },
  { flag: 'sa_passato_bardo',   icon: '🎻', title: 'Biografi Non Autorizzati',      desc: 'Conoscete il segreto imbarazzante di Lord Vesper Morn: sapeva cantare.' },
  { flag: 'benedizione',        icon: '✨', title: 'Benedetti al Quarto Giorno',    desc: 'Pipino vi ha benedetto a caso, ed è pure funzionato.' },
  { flag: 'sa_ballo',           icon: '🕺', title: 'Amici dei Goblin',              desc: 'Avete fatto pace (o affari) coi Goblin Riuniti del Turno di Notte.' },
  { flag: 'sa_corona',          icon: '👑', title: 'La Colpa È della Corona',       desc: 'Avete scoperto che il vero nemico non è Vesper, ma ciò che porta in testa.' },
  { flag: 'burocrazia_battuta', icon: '📋', title: 'Terrore degli Uffici Reclami',  desc: 'Avete compilato un modulo alla perfezione. Gli scheletri vi rispettano.' },
  { flag: 'sa_gerbold',         icon: '🫖', title: 'Orecchie Fini al Buffet',       desc: 'Avete origliato abbastanza da scoprire che pure il maggiordomo è esausto.' },
  { flag: 'gerbold_alleato',    icon: '🏖️', title: 'Sindacalisti per Scheletri',    desc: 'Avete convinto Gerbold a licenziarsi su due femori.' },
  { flag: 'capra_salvata',      icon: '🐐', title: 'Salvatori di Berenice',         desc: 'Avete recuperato la capra di Bocciolo dal tetto del tempietto. Di nuovo.' },

  // ---- flag NUOVI: richiedono una piccola aggiunta a campaign.js (vedi report) ----
  { flag: 'via_bosco',              icon: '🌲', title: 'Sussurratori di Alberi',      desc: 'Avete scelto la via del Bosco dei Sussurri, e siete sopravvissuti al gossip.' },
  { flag: 'via_miniere',            icon: '⛏️', title: 'Amici dei Nani Paranoici',    desc: 'Avete scelto la via delle Miniere di Ferrovecchio, superando l\'interrogatorio.' },
  { flag: 'fatto_ridere_ortica',    icon: '😂', title: 'Comici Sopraffini',           desc: 'Avete fatto ridere una strega per la prima volta in duecento anni.' },
  { flag: 'finale_vittoria',        icon: '🏆', title: 'Il Sole Torna sul Serio',     desc: 'Avete sconfitto Vesper in battaglia e distrutto la Corona.' },
  { flag: 'finale_redenzione',      icon: '🎶', title: 'Un Vampiro Redento',          desc: 'Avete convinto Vespertino a scegliere un applauso vero, non la vendetta.' },
  { flag: 'finale_corona_distrutta', icon: '💥', title: 'Corona in Mille Pezzi',      desc: 'Avete strappato la Corona di Mezzanotte prima che fosse troppo tardi.' },
  { flag: 'via_fiume',              icon: '🛶', title: 'Marinai d\'Acqua Dolce',       desc: 'Avete scelto la via del Fiume Torbido, rapide e fantasmi compresi.' },
  { flag: 'bertoldo_amico',         icon: '👻', title: 'Amici di un Fantasma Bagnato', desc: 'Avete ascoltato la storia di Bertoldo. Nessuno gliel\'aveva mai chiesta.' },
  { flag: 'lacrima_ceduta',         icon: '🌙', title: 'Un Ricordo per la Luce',       desc: 'Qualcuno di voi ha ceduto un ricordo felice al Pescatore. Per tutti.' },
  { flag: 'lacrima_usata',          icon: '🌅', title: 'La Scelta della Taverna',      desc: 'Con una lacrima e un ricordo avete salvato il mondo senza sguainare la spada.' },
  { flag: 'sa_corvo',               icon: '🐦‍⬛', title: 'Amici del Critico',           desc: 'Avete capito Amleto Dellacroce, corvo ed ex critico musicale. Lui ha capito voi.' },
  { flag: 'tentazione_resistita',   icon: '🛡️', title: 'Più Forti della Corona',       desc: 'La Corona di Mezzanotte vi ha sussurrato. Le avete risposto di no.' },
  { flag: 'tentazione_ceduta',      icon: '👑', title: 'Il Regno dei Quattro Secondi', desc: 'Uno di voi ha regnato sull\'oscurità per quattro secondi esatti. Che regno, però.' },
];

/* ==================== CRONACHE DI LUMELIA ====================
   Righe d'epilogo che compaiono SOLO se avete vissuto quella storia:
   il finale riflette le scelte fatte lungo la strada.              */

const CRONACA = [
  { flag: 'sa_ballo',            icon: '✊', text: 'I Goblin Riuniti del Turno di Notte hanno ottenuto il primo contratto collettivo della storia di Lumelia. Gruk è stato eletto sindaco del suo ponte, carica che esercita con megafono e fascia tricolore.' },
  { flag: 'gerbold_alleato',     icon: '🏖️', text: 'Gerbold è tornato dalla sua prima vacanza al mare con un colorito ("È SABBIA, ma apprezzo l\'ottimismo") e ha fondato "Dignità & Argenteria", agenzia di maggiordomi con ferie garantite. Ha già dodici iscritti e un fantasma in prova.' },
  { flag: 'fatto_ridere_ortica', icon: '😂', text: 'Nonna Ortica ha riso altre tre volte, quest\'anno. Il Bosco dei Sussurri non parla d\'altro. Il gatto ha chiesto di cambiare capanna.' },
  { flag: 'remo_ritrovato',      icon: '🚣', text: 'Bertoldo naviga di nuovo con il remo di suo padre. Dicono che nelle notti calme lo si senta fischiettare sulle rapide — intonato, per la prima volta in centocinquant\'anni.' },
  { flag: 'bertoldo_amico',      icon: '👻', text: 'Alla Corporazione dei Barcaioli è arrivato un reclamo scritto con grafia ottocentesca: Bertoldo esige gli arretrati di 150 anni di straordinari. La pratica è in valutazione. Lui non ha fretta.' },
  { flag: 'capra_salvata',       icon: '🐐', text: 'Berenice è tornata sul tetto del tempietto il giorno dopo. Nessuno sa come. Nessuno osa più chiederlo. Pipino ha aggiunto una scala, che lei ignora per principio.' },
  { flag: 'burocrazia_battuta',  icon: '📋', text: 'Il vostro Modulo 7-B è esposto in una teca nell\'Ufficio Reclami del Sottosuolo, con la dicitura "ESEMPLARE UNICO — NON TOCCARE". Gli scheletri ci portano i tirocinanti in pellegrinaggio.' },
  { flag: 'sa_corvo',            icon: '🐦‍⬛', text: 'Amleto Dellacroce ha ripreso a pubblicare recensioni, incise a beccate sulle staccionate del regno. Sono temute, attese e sorprendentemente giuste. Il pane di Brindolo è migliorato del 40%.' },
  { flag: 'benedizione',         icon: '⛪', text: 'Pipino è stato promosso a chierico di prima classe. Il manuale, nella nuova edizione, ha finalmente un capitolo sul sole spento. L\'ha scritto lui.' },
  { flag: 'lacrima_ceduta',      icon: '🌙', text: 'Il Pescatore di Ricordi custodisce ancora quel ricordo felice. A volte, nelle notti giuste, lo lascia galleggiare in superficie perché il fiume lo porti a chi ne ha più bisogno. Funziona.' },
  { flag: 'tentazione_ceduta',   icon: '🤫', text: 'Del Regno dei Quattro Secondi non si parla. MAI. (Il sovrano deposto paga ancora da bere a chi promette silenzio.)' },
  { flag: 'tentazione_resistita', icon: '🛡️', text: 'La storia di chi disse no alla Corona è diventata una parabola che si racconta ai bambini di Lumelia. La morale cambia a ogni racconto, ma il finale è sempre lo stesso: "e per questo il sole sorge ancora".' },
  { flag: 'solo',                icon: '🌟', text: 'E i bardi ancora discutono: com\'è possibile che UN SOLO eroe abbia fatto tutto questo? La risposta, come sempre, è: pozioni. Tante, tante pozioni.' },
  /* ---- TRE SCELTE CHE PRIMA NON LASCIAVANO TRACCIA ----
     Lo strumento dei flag orfani (24 agosto 2026) ha trovato cinque scelte il cui unico
     effetto era un flag che non leggeva nessuno: tre erano di racconto e stanno qui, due
     avevano bisogno di un effetto vero e l'hanno avuto. */
  { flag: 'avviso_ragout',     icon: '🍲', text: 'Monsieur Ragoût ha aggiunto una portata al menù eterno del Banchetto, la ottava, e sul cartoncino scritto a mano c\'è: <i>«Sorbetto di cortesia — offerto da chi mi ha detto la verità»</i>. Non l\'ha assaggiata nessuno perché nessuno mangia, al Banchetto. Ma il cartoncino sta lì, e i cartoncini, in questo castello, contano più delle portate.' },
  { flag: 'ribellione_ragout', icon: '📜', text: 'Sulla porta delle cucine, da qualche mese, è affisso un foglio con una lista di rivendicazioni in ventidue punti, in calligrafia impeccabile. Il punto uno chiede le ferie arretrate dal 1841. Il punto ventidue chiede «un commensale, uno solo, che finisca il piatto». Vesper non ha risposto: ha fatto incorniciare il foglio, che è la cosa più crudele che gli riusciva.' },
  { flag: 'banditi_a_casa',    icon: '🗺', text: 'Tre banditi da strada, che erano usciti di casa per rapinare qualcuno e sono tornati indietro perché qualcuno ha tenuto il braccio fermo abbastanza a lungo da farsi capire, hanno aperto una locanda sulla via del bosco. Si chiama <i>Al Braccio Fermo</i>, il vino è annacquato e la strada, per la prima volta in trent\'anni, è sicura.' },
];
